'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),sharp=require('sharp');
const {memory}=require('./helpers/repository-memory');
const {sync}=require('../lib/repository-dropbox-sync');
const {ROOT,ROOT_ID,digest}=require('../lib/repository-dropbox-storage');
const {browse}=require('../lib/repository-library-browse');
async function setup(){const deps=memory(),bytes=await sharp({create:{width:2,height:2,channels:3,background:'red'}}).png().toBuffer();const m={'.tag':'file',id:'id:external',rev:'r1',name:'Historical press.png',path_display:ROOT+'/Historical press.png',path_lower:(ROOT+'/Historical press.png').toLowerCase(),size:bytes.length};let page={entries:[m],cursor:'c1',has_more:false};deps.dropbox={changes:async()=>page,metadata:async id=>id===ROOT?{'.tag':'folder',id:ROOT_ID,path_display:ROOT,path_lower:ROOT.toLowerCase()}:m,read:async()=>bytes,preview:async()=>({fileId:'id:preview',rev:'p1'})};return {deps,m,setPage:p=>{page=p;}};}
test('sync imports once, persists cursor, skips previews, and preserves edited prose',async()=>{const {deps,m,setPage}=await setup();await sync(deps,{force:true});const id='entry-'+digest(m.id).slice(0,32),path='entries/'+id;assert.equal(deps.records.get(path).sourceType,'unspecified');assert.equal(deps.records.get('repositoryLibrarySync/dropbox').cursor,'c1');deps.records.get(path).description='Hand edited';setPage({entries:[m,{...m,path_lower:(ROOT+'/_previews/p.webp').toLowerCase()}],cursor:'c2',has_more:false});await sync(deps,{force:true});assert.equal(deps.records.get(path).description,'Hand edited');assert.equal(deps.records.get(path).version,1);assert.equal([...deps.records.keys()].filter(k=>k.startsWith('entries/')).length,1);});
test('processing failure does not advance cursor and concurrent lease prevents work',async()=>{const {deps}=await setup();deps.dropbox.read=async()=>{throw Error('Unavailable');};await assert.rejects(sync(deps,{force:true}));assert(!deps.records.get('repositoryLibrarySync/dropbox').cursor);deps.records.set('repositoryLibrarySync/dropbox',{leaseUntil:Date.now()+50000,leaseOwner:'other'});assert.equal((await sync(deps,{force:true})).status,'current_or_syncing');});
test('folder deletion marks descendant images unavailable without deleting records',async()=>{const {deps,setPage}=await setup();for(let i=0;i<3;i++)deps.records.set('entries/entry-'+i,{entryId:'entry-'+i,kind:'image',version:1,folderId:'f',imageAncestorIds:['f'],dropboxPathLower:(ROOT+'/old/'+i+'.png').toLowerCase()});setPage({entries:[{'.tag':'deleted',path_lower:(ROOT+'/old').toLowerCase()}],cursor:'deleted',has_more:false});await sync(deps,{force:true});for(let i=0;i<3;i++){const e=deps.records.get('entries/entry-'+i);assert.equal(e.availability,'unavailable');assert.equal(e.activeKind,'unavailable');assert.deepEqual(e.imageAncestorIds,[]);}});
test('search stops at its read budget and continues from scanned cursor even with no matches',async()=>{const deps=memory();for(let i=0;i<305;i++){const entryId='entry-'+String(i).padStart(4,'0');deps.records.set('entries/'+entryId,{entryId,kind:'image',activeKind:'image',title:i===304?'needle':'hay',version:1});}const one=await browse({operation:'search',query:'needle',kind:'image'},deps);assert.equal(one.count,0);assert.equal(one.coverage.scanned,300);assert(one.nextAfter);const two=await browse({operation:'search',query:'needle',kind:'image',after:one.nextAfter},deps);assert.equal(two.count,1);assert.equal(two.nextAfter,null);assert(deps.reads.every(r=>r.limit<=300));});

test('unfiltered catalog totals exclude unavailable tombstones',async()=>{const deps=memory({'entries/entry-a':{entryId:'entry-a',kind:'image',activeKind:'image',title:'live'},'entries/entry-b':{entryId:'entry-b',kind:'image',activeKind:'unavailable',availability:'unavailable',title:'gone'}});const result=await browse({operation:'search'},deps);assert.equal(result.totalMatches,1);assert.equal(result.count,1);});
