'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {DropboxStorage,ROOT,inside,segment,digest}=require('../lib/repository-dropbox-storage');
const {link,verify}=require('../lib/repository-image-links');
function provider({conflict=false,changed=false,outside=false}={}){
 const data=Buffer.from('original'),meta={'.tag':'file',id:'id:file',rev:'revision',size:data.length,path_lower:(ROOT+'/image.png').toLowerCase(),path_display:ROOT+'/image.png'};let calls=[];
 const store=new DropboxStorage({refreshToken:'test-refresh',fetchImpl:async(url,init)=>{calls.push({url,init});if(url.endsWith('/oauth2/token'))return Response.json({access_token:'test-token',expires_in:3600});if(url.endsWith('/get_metadata'))return Response.json({...meta,rev:changed?'changed':'revision',path_lower:outside?'/outside/image.png':meta.path_lower});if(url.endsWith('/upload'))return conflict?Response.json({error:{'.tag':'path',path:{'.tag':'conflict'}}},{status:409}):Response.json({...meta,'.tag':undefined});if(url.endsWith('/download'))return new Response(data,{headers:{'dropbox-api-result':JSON.stringify(meta)}});throw Error('Unexpected request');}});
 return {store,data,meta,calls};
}
test('upload verifies original bytes and accepts concrete FileMetadata receipt',async()=>{const {store,data,calls}=provider();const ref=await store.put(ROOT+'/image.png',data);assert.equal(ref.checksumSha256,digest(data));assert.equal(calls.filter(c=>c.url.endsWith('/oauth2/token')).length,1);assert(calls.some(c=>c.url.endsWith('/download')));});
test('retry never overwrites a conflicting file and detects different bytes',async()=>{const {store,data,calls}=provider({conflict:true});await store.put(ROOT+'/image.png',data);await assert.rejects(store.put(ROOT+'/image.png',Buffer.from('different')),/checksum mismatch/);const upload=calls.find(c=>c.url.endsWith('/upload'));assert.equal(JSON.parse(upload.init.headers['Dropbox-API-Arg']).mode,'add');});
test('root boundaries and revision changes reject access',async()=>{for(const p of ['/elsewhere',ROOT+'-other/image',ROOT+'/../escape',ROOT+'/x\\escape'])assert(!inside(p));assert(inside(ROOT+'/a.png'));assert(!segment('../a/b').includes('/'));for(const option of [{changed:true},{outside:true}]){const {store}=provider(option);await assert.rejects(store.read({fileId:'id:file',rev:'revision'}));}const {store}=provider();await assert.rejects(store.put('/outside',Buffer.from('x')));});
test('private links reject tampering, wrong signing key, expiry, and invalid variants',()=>{const now=1000000,deps={mediaKey:'test-signing-key',mediaOrigin:'https://example.test'},entry={entryId:'entry-abc',version:2};const value=link(entry,'original','staff',deps,now),token=value.url.split('/').at(-1);assert.equal(verify(token,deps.mediaKey,now).subject,'staff');for(const [t,k,n] of [[token+'a',deps.mediaKey,now],[token,'wrong',now],[token,deps.mediaKey,now+900000]])assert.throws(()=>verify(t,k,n));assert.throws(()=>verify(link(entry,'bad','staff',deps,now).url.split('/').at(-1),deps.mediaKey,now));});
