steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-f', 'services/maintenance-worker/Dockerfile', '-t', '${_IMAGE}', '.']
images: ['${_IMAGE}']
substitutions:
  _IMAGE: us-west1-docker.pkg.dev/location-map-985/cloud-run-source-deploy/fbc-maintenance-messaging-worker:review
